-- 문제 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/59405

-- MYSQL
SELECT NAME
FROM ANIMAL_INS
ORDER BY DATETIME
LIMIT 1;

-- ORACLE
SELECT NAME
FROM (
    SELECT *
    FROM ANIMAL_INS
    ORDER BY DATETIME)
WHERE ROWNUM = 1;