-- 문제 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/144853

-- MYSQL
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE CATEGORY = '인문' AND PUBLISHED_DATE LIKE '2021%'
ORDER BY PUBLISHED_DATE ASC;

-- ORACLE
SELECT BOOK_ID, TO_CHAR(PUBLISHED_DATE, 'yyyy-mm-dd') AS PUBLISHED_DATE
FROM BOOK
WHERE CATEGORY = '인문' AND TO_CHAR(PUBLISHED_DATE, 'yyyy') = '2021'
ORDER BY PUBLISHED_DATE ASC;