-- 문제 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/131118

-- MYSQL
(SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
       PRODUCT_ID,
       USER_ID,
       SALES_AMOUNT
FROM ONLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') LIKE ('2022-03'))
UNION ALL
(SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') AS SALES_DATE,
       PRODUCT_ID,
       NULL AS USER_ID,
       SALES_AMOUNT
FROM OFFLINE_SALE
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') LIKE ('2022-03')
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC));

-- ORACLE
(SELECT TO_CHAR(SALES_DATE, 'yyyy-mm-dd') AS SALES_DATE,
       PRODUCT_ID,
       USER_ID,
       SALES_AMOUNT
FROM ONLINE_SALE
WHERE TO_CHAR(SALES_DATE, 'yyyy-mm') LIKE ('2022-03'))
UNION ALL
(SELECT TO_CHAR(SALES_DATE, 'yyyy-mm-dd') AS SALES_DATE,
       PRODUCT_ID,
       NULL AS USER_ID,
       SALES_AMOUNT
FROM OFFLINE_SALE
WHERE TO_CHAR(SALES_DATE, 'yyyy-mm') LIKE ('2022-03')
ORDER BY SALES_DATE ASC, PRODUCT_ID ASC, USER_ID ASC));

/*
 UNION / UNION ALL과 FULL OUTER JOIN의 차이점
    * UNION : 일치하는 column만 반환
    * FULL OUTER JOIN : 일치하지 않는 column도 모두 반환

 => 위 문제에서는 UNION을 사용해야하는 문제!
 */