-- 문제 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/131533

-- MYSQL
SELECT A.PRODUCT_CODE AS 'PRODUCT_CODE', SUM (A.PRICE * B.SALES_AMOUNT) AS 'SALES'
FROM PRODUCT A INNER JOIN OFFLINE_SALE B ON A.PRODUCT_ID = B.PRODUCT_ID
GROUP BY A.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE;