-- 문제 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/59044

-- MYSQL
SELECT A.NAME,
       A.DATETIME
FROM ANIMAL_INS A
         LEFT OUTER JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
WHERE B.ANIMAL_ID IS NULL
ORDER BY A.DATETIME LIMIT 3;

-- ORACLE
-- * ROWNUM의 경우, SELECT 수행 전에 수행되기 때문에 ORDER BY 조건을 타지 않아 서브쿼리로 나타내야함!!
SELECT *
FROM (SELECT A.NAME, A.DATETIME
      FROM ANIMAL_INS A
               LEFT OUTER JOIN ANIMAL_OUTS B ON A.ANIMAL_ID = B.ANIMAL_ID
      WHERE B.ANIMAL_ID IS NULL
      ORDER BY A.DATETIME)
WHERE ROWNUM <= 3;