-- 문제 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/144855

-- MYSQL
SELECT A.CATEGORY AS 'CATEGORY', SUM(B.SALES) AS 'TOTAL_SALES'
FROM BOOK A INNER JOIN BOOK_SALES B ON A.BOOK_ID = B.BOOK_ID
WHERE B.SALES_DATE LIKE '2022-01%'
GROUP BY A.CATEGORY
ORDER BY CATEGORY;