-- 문제 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/131118

-- MYSQL & ORACLE
SELECT INFO.REST_ID AS REST_ID,
       INFO.REST_NAME AS REST_NAME,
       INFO.FOOD_TYPE AS FOOD_TYPE,
       INFO.FAVORITES AS FAVORITES,
       INFO.ADDRESS AS ADDRESS,
       ROUND(AVG(REVIEW.REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO INFO, REST_REVIEW REVIEW
WHERE INFO.REST_ID = REVIEW.REST_ID
  AND INFO.ADDRESS LIKE ('서울%')
GROUP BY INFO.REST_ID, INFO.REST_NAME, INFO.FOOD_TYPE, INFO.FAVORITES, INFO.ADDRESS
ORDER BY SCORE DESC, FAVORITES DESC;